version: '3.8'

services:
  # Nginx as frontend proxy
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./examples/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mata
    networks:
      - mata-net

  # Mata traffic duplicator
  mata:
    build: .
    command: ["./mata", "-source", ":8080", "-targets", "app:8000,analytics:8000"]
    networks:
      - mata-net
    depends_on:
      - app
      - analytics

  # Main application service
  app:
    image: python:3.9-alpine
    command: ["python", "-m", "http.server", "8000"]
    working_dir: /app
    volumes:
      - ./examples/app:/app
    networks:
      - mata-net

  # Analytics/monitoring service
  analytics:
    image: python:3.9-alpine
    command: ["python", "-m", "http.server", "8000"]
    working_dir: /analytics
    volumes:
      - ./examples/analytics:/analytics
    networks:
      - mata-net

networks:
  mata-net:
    driver: bridge